export const START_GET_USERS = "START_GET_USERS";
export const SUCCESS_GET_USERS = "SUCCESS_GET_USERS";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";